---

- name: Configure router 1
  hosts: ruter1
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Load variables
      ansible.builtin.include_vars: variables.yaml

    - name: Set up outside interface
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.254.2 255.255.255.252
          - no shutdown
        parents: "interface GigabitEthernet0/1"

    - name: Enable inside interface
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: "interface GigabitEthernet0/0"

    - name: Set up inside subinterface 10
      cisco.ios.ios_config:
        lines:
          - encapsulation dot1q 10
          - ip address 192.168.10.2 255.255.255.0
          - no shutdown
          - standby 10 ip 192.168.10.1
          - standby 10 priority 110
          - standby 10 preempt
          - standby 10 timers 1 3
        parents: "interface GigabitEthernet0/0.10"

    - name: Set up inside subinterface 99
      cisco.ios.ios_config:
        lines:
          - encapsulation dot1q 99
          - ip address 192.168.99.2 255.255.255.0
          - no shutdown
          - standby 99 ip 192.168.99.1
          - standby 99 priority 110
          - standby 99 preempt
          - standby 99 timers 1 3
        parents: "interface GigabitEthernet0/0.99"

    - name: configure OSPF
      cisco.ios.ios_config:
        lines:
          - router-id 2.1.1.1
          - network 192.168.254.0 0.0.0.3 area 0
          - network 192.168.10.0 0.0.0.255 area 1
          - network 192.168.99.0 0.0.0.255 area 1
        parents: router ospf 10

    - name: configure DHCP
      cisco.ios.ios_config:
        lines:
          - network 192.168.10.0 255.255.255.0
          - dns-server 192.168.10.1
          - default-router 192.168.10.1
        parents: "ip dhcp pool test" 
    - name: exclude addresses handled by other router
      cisco.ios.ios_config:
        lines:
          - ip dhcp excluded-address 192.168.10.127 192.168.10.254
      
